### PR TITLE
Update multimap documentation

### PR DESCRIPTION
**Pull request by fatalbanana**

### CODE REVIEW

**Comment by moisseev** [comment]
What is "message source"?
https://github.com/vstakhov/rspamd.com/pull/107/commits/2cef71410c59e824d1e61a431742a7f375d9b120#diff-6b5446bfa897a3e6a4780a9e288a580aR106
"source IP of message" is ambiguous as well.

**Comment by fatalbanana** [comment]
Can you suggest something clearer? :)

**Comment by moisseev** [comment]
I'm afraid it's too hard for me to phrase it, especially in English.
Strictly speaking, I think message can't have an IP and we are using SMTP session sender IP, but message header contains multiple source IPs that can be confused. I think the description should clearly point to the IP address of the last hop SMTP client somehow.

**Comment by fatalbanana** [comment]
I find it hard too. :) (particularly to balance this with being concise)

I would say that a message has only one source though, everything else is a hop.

**Comment by moisseev** [comment]
Then message source IP is MUA host IP ;)

**Comment by fatalbanana** [comment]
That is indeed a way of looking at it. Your MTA considers message source to be whatever hands off to it though.

**Pull request merged**
