### PR TITLE
Document outbound scanning somewhat

### PR DESCRIPTION
**Pull request by fatalbanana**

### CODE REVIEW

**Comment by fatalbanana** [comment]
@moisseev ;)

**Comment by moisseev** [comment]
@fatalbanana What?

1. Thank you very much. :+1: 
2. Rspamd should be capitalized.
3. `s/eg\./e\.g\./`
4. Are `local_addrs` treated exactly as authenticated users?

**Comment by fatalbanana** [comment]
1. :)
2. Bah. ;)
3. Ok. ;)
4. `local_addrs` should generally be considered in conjunction with authentication. The exceptions are hfilter (which looks at authentication only for now but will be fixed ;)) and RBL (which can consider these individually).

**Comment by moisseev** [comment]
Capitalization still needs attention. ;)    
I might be worth to introduce another list of trusted hosts/nets instead that unable to authenticate but treated exactly as authenticated users. And make `local_addrs` not too relaxed.

**Pull request merged**
